"""Event bus package (ADR-0041 — Redis Streams).

Public API::

    from personal_agent.events import (
        EventBus,
        EventHandler,
        NoOpBus,
        get_event_bus,
        set_global_event_bus,
        EventBase,
        RequestCapturedEvent,
        STREAM_REQUEST_CAPTURED,
        CG_CONSOLIDATOR,
    )
"""

from personal_agent.events.bus import (
    EventBus,
    EventHandler,
    NoOpBus,
    get_event_bus,
    set_global_event_bus,
)
from personal_agent.events.models import (
    CG_CONSOLIDATOR,
    CG_ES_INDEXER,
    CG_FRESHNESS,
    CG_MODE_CONTROLLER,
    CG_SESSION_WRITER,
    CG_TURN_PROJECTOR,
    STREAM_MEMORY_ACCESSED,
    STREAM_MEMORY_ENTITIES_UPDATED,
    STREAM_METRICS_SAMPLED,
    STREAM_MODE_TRANSITION,
    STREAM_REQUEST_CAPTURED,
    STREAM_REQUEST_COMPLETED,
    STREAM_TURN_OBSERVED,
    AccessContext,
    EventBase,
    MemoryAccessedEvent,
    MemoryEntitiesUpdatedEvent,
    MetricsSampledEvent,
    ModelCallCompletedEvent,
    ModeTransitionEvent,
    RequestCapturedEvent,
    RequestCompletedEvent,
    SubAgentProgressEvent,
    TopologyEnteredEvent,
    TurnCompletedEvent,
    TurnDegradedEvent,
    TurnProgressEvent,
    parse_stream_event,
)

__all__ = [
    "AccessContext",
    "CG_CONSOLIDATOR",
    "CG_ES_INDEXER",
    "CG_FRESHNESS",
    "CG_MODE_CONTROLLER",
    "CG_SESSION_WRITER",
    "CG_TURN_PROJECTOR",
    "EventBase",
    "EventBus",
    "EventHandler",
    "MemoryAccessedEvent",
    "MemoryEntitiesUpdatedEvent",
    "MetricsSampledEvent",
    "ModelCallCompletedEvent",
    "ModeTransitionEvent",
    "NoOpBus",
    "RequestCapturedEvent",
    "RequestCompletedEvent",
    "STREAM_MEMORY_ACCESSED",
    "STREAM_MEMORY_ENTITIES_UPDATED",
    "STREAM_METRICS_SAMPLED",
    "STREAM_MODE_TRANSITION",
    "STREAM_REQUEST_CAPTURED",
    "STREAM_REQUEST_COMPLETED",
    "STREAM_TURN_OBSERVED",
    "TopologyEnteredEvent",
    "TurnCompletedEvent",
    "TurnDegradedEvent",
    "TurnProgressEvent",
    "SubAgentProgressEvent",
    "get_event_bus",
    "parse_stream_event",
    "set_global_event_bus",
]
