"""Types for the expansion controller.

The expansion controller enforces deterministic sub-agent dispatch when
the gateway sets strategy ∈ {HYBRID, DECOMPOSE}. These types define the
plan schema, phase tracking, and sub-agent execution modes.

See: ADR-0036 (expansion-controller), ADR-0035 (seshat-backend-decision)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

from personal_agent.orchestrator.worker_types import Thoroughness, WorkerType


class SubAgentMode(Enum):
    """Execution mode for a sub-agent task.

    PARALLEL_INFERENCE: A focused LLM call, optionally with a bounded tool loop
        when the task requests tools that clear the sub-agent tool grant
        (FRE-1388/FRE-1389). Used for analysis, comparison, and synthesis
        sub-tasks.
    """

    PARALLEL_INFERENCE = "parallel_inference"


class ExpansionPhase(Enum):
    """Phases of the expansion controller state machine."""

    PLANNING = "planning"
    DISPATCH = "dispatch"
    SYNTHESIS = "synthesis"


@dataclass(frozen=True)
class PlanTask:
    """A single sub-task within an expansion plan.

    Produced by the LLM planner or deterministic fallback planner.
    Consumed by the executor dispatch phase.

    Args:
        name: Task identifier (e.g., "compare_performance").
        goal: What this sub-agent should answer or produce.
        type: The registry worker type that runs this task (ADR-0150 D2). The
            type, not the planner, decides the tools, the prompt block and the
            report shape; the per-task ``tools`` list and free-text
            ``expected_output`` this field replaced are gone.
        thoroughness: The task's named level (ADR-0150 D3), mapped to a round
            budget by ``settings.sub_agent_rounds_for``.
        constraints: Scope or focus limits for the sub-agent.
        mode: Execution mode (currently always PARALLEL_INFERENCE).
    """

    name: str
    goal: str
    type: WorkerType
    thoroughness: Thoroughness
    constraints: list[str] = field(default_factory=list)
    mode: SubAgentMode = SubAgentMode.PARALLEL_INFERENCE


@dataclass(frozen=True)
class ExpansionPlan:
    """A validated expansion plan ready for dispatch.

    Args:
        strategy: "HYBRID" or "DECOMPOSE" — mirrors gateway output.
        tasks: Ordered list of sub-tasks to execute.
        is_fallback: True if generated by the deterministic fallback planner.
    """

    strategy: str
    tasks: list[PlanTask]
    is_fallback: bool = False


@dataclass(frozen=True)
class PhaseResult:
    """Result of a single expansion phase.

    Args:
        phase: Which phase completed.
        duration_ms: Wall-clock time for this phase.
        success: Whether the phase completed without error.
        error: Error description if success is False.
    """

    phase: ExpansionPhase
    duration_ms: float
    success: bool
    error: str | None = None


@dataclass(frozen=True)
class SubAgentInterval:
    """Wall-clock window one sub-agent occupied during dispatch (FRE-1380 AC-1).

    Recorded around each dispatch call so serialization can be verified from real
    timestamps rather than from the dispatch implementation asserting its own semaphore
    value.

    Args:
        task_name: The plan task's name.
        start_monotonic: ``time.monotonic()`` reading when this task's dispatch began.
        end_monotonic: ``time.monotonic()`` reading when this task's dispatch ended
            (success, failure, or a raised exception — always recorded).
    """

    task_name: str
    start_monotonic: float
    end_monotonic: float
