"""Types for the expansion controller.

The expansion controller enforces deterministic sub-agent dispatch when
the gateway sets strategy ∈ {HYBRID, DECOMPOSE}. These types define the
plan schema, phase tracking, and sub-agent execution modes.

See: ADR-0036 (expansion-controller), ADR-0035 (seshat-backend-decision)
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from enum import Enum
from typing import Literal

from personal_agent.orchestrator.worker_types import Thoroughness, WorkerType

#: Why queued plan tasks were never dispatched. One fan-out has at most one reason:
#: both skips hold for every task after the first one skipped.
#:
#: ``turn_budget`` — the turn's remaining budget was exhausted (FRE-1397).
#: ``origin_error`` — an earlier worker's model server answered 5xx, so no sibling
#: was sent into it (FRE-1501).
SkipReason = Literal["turn_budget", "origin_error"]

#: The clause that completes "The following sub-tasks were not run — ...".
SKIP_REASON_TEXT: dict[SkipReason, str] = {
    "turn_budget": "the turn's time budget was exhausted before dispatch reached them",
    "origin_error": "the model server failed on an earlier sub-task, so they were not sent to it",
}


class SubAgentMode(Enum):
    """Execution mode for a sub-agent task.

    PARALLEL_INFERENCE: A focused LLM call, optionally with a bounded tool loop
        when the task requests tools that clear the sub-agent tool grant
        (FRE-1388/FRE-1389). Used for analysis, comparison, and synthesis
        sub-tasks.
    """

    PARALLEL_INFERENCE = "parallel_inference"


class ExpansionPhase(Enum):
    """Phases of the expansion controller state machine."""

    PLANNING = "planning"
    DISPATCH = "dispatch"
    SYNTHESIS = "synthesis"


@dataclass(frozen=True)
class PlanTask:
    """A single sub-task within an expansion plan.

    Produced by the LLM planner or deterministic fallback planner.
    Consumed by the executor dispatch phase.

    Args:
        name: Task identifier (e.g., "compare_performance").
        goal: What this sub-agent should answer or produce.
        type: The registry worker type that runs this task (ADR-0150 D2). The
            type, not the planner, decides the tools, the prompt block and the
            report shape; the per-task ``tools`` list and free-text
            ``expected_output`` this field replaced are gone.
        thoroughness: The task's named level (ADR-0150 D3), mapped to a round
            budget by ``settings.sub_agent_rounds_for``.
        constraints: Scope or focus limits for the sub-agent.
        mode: Execution mode (currently always PARALLEL_INFERENCE).
    """

    name: str
    goal: str
    type: WorkerType
    thoroughness: Thoroughness
    constraints: list[str] = field(default_factory=list)
    mode: SubAgentMode = SubAgentMode.PARALLEL_INFERENCE


@dataclass(frozen=True)
class ExpansionPlan:
    """A validated expansion plan ready for dispatch.

    Args:
        strategy: "HYBRID" or "DECOMPOSE" — mirrors gateway output.
        tasks: Ordered list of sub-tasks to execute.
        is_fallback: True if generated by the deterministic fallback planner.
    """

    strategy: str
    tasks: list[PlanTask]
    is_fallback: bool = False


@dataclass(frozen=True)
class PhaseResult:
    """Result of a single expansion phase.

    Args:
        phase: Which phase completed.
        duration_ms: Wall-clock time for this phase.
        success: Whether the phase completed without error.
        error: Error description if success is False.
    """

    phase: ExpansionPhase
    duration_ms: float
    success: bool
    error: str | None = None


@dataclass(frozen=True)
class SubAgentInterval:
    """Wall-clock window one sub-agent occupied during dispatch (FRE-1380 AC-1).

    Recorded around each dispatch call so serialization can be verified from real
    timestamps rather than from the dispatch implementation asserting its own semaphore
    value.

    Args:
        task_name: The plan task's name.
        start_monotonic: ``time.monotonic()`` reading when this task's dispatch began.
        end_monotonic: ``time.monotonic()`` reading when this task's dispatch ended
            (success, failure, or a raised exception — always recorded).
    """

    task_name: str
    start_monotonic: float
    end_monotonic: float


@dataclass(frozen=True)
class MemoryItemKey:
    """The compound key of one memory item in a digest (ADR-0147 D1, FRE-1471 AC-6).

    An identity alone is not a key: two entities can share a name, and an item whose
    identity cannot be resolved collapses to the empty string. The ordinal separates them.
    A comparison of keys is an ordered multiset comparison, never a set comparison.

    Args:
        kind: The item kind, a ``MemoryItemKind`` value.
        identity: The item identity from ``memory_item_identity``. It can be empty.
        ordinal: The 0-based position of the item in the shared selection's output, which
            is the relevance order. It is not the renderer's section order.
    """

    kind: str
    identity: str
    ordinal: int


@dataclass(frozen=True)
class PlannerMemoryDigest:
    """A bounded, one-line-per-item digest of the memory the primary renders (ADR-0147 D1, D4).

    Built from the renderer's own selection and text helpers, so no line carries a fact or a
    wording that the primary's memory section does not carry.

    Args:
        text: The digest lines joined by newlines. Empty when there is nothing to say.
        item_keys: One key per emitted line, in order.
        rendered_item_keys: One key per item the renderer emits, in the shared selection's
            order (relevance order). The ``item_keys`` are an ordered sub-multiset of these.
        item_count: The number of lines in ``text``.
        eligible_count: The number of items the shared selection returned.
        dropped_count: The number of lines the token ceiling dropped from the tail. The
            item cap does not count here.
        kind_counts: The number of emitted lines for each item kind.
        max_line_chars: The length of the longest emitted line. Zero when empty.
        estimated_tokens: The estimated token size of ``text``.
    """

    text: str
    item_keys: tuple[MemoryItemKey, ...]
    rendered_item_keys: tuple[MemoryItemKey, ...]
    item_count: int
    eligible_count: int
    dropped_count: int
    kind_counts: Mapping[str, int]
    max_line_chars: int
    estimated_tokens: int
