"""Types for the expansion controller.

The expansion controller enforces deterministic sub-agent dispatch when
the gateway sets strategy ∈ {HYBRID, DECOMPOSE}. These types define the
plan schema, phase tracking, and sub-agent execution modes.

See: ADR-0036 (expansion-controller), ADR-0035 (seshat-backend-decision)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum


class SubAgentMode(Enum):
    """Execution mode for a sub-agent task.

    PARALLEL_INFERENCE: Fire-and-forget LLM call, no tool access.
        Used for analysis, comparison, and synthesis sub-tasks.
    TOOLED_SEQUENTIAL: Mini tool-use loop with MCP tool access.
        Used for research sub-tasks that need web search or other tools.
    """

    PARALLEL_INFERENCE = "parallel_inference"
    TOOLED_SEQUENTIAL = "tooled_sequential"


class ExpansionPhase(Enum):
    """Phases of the expansion controller state machine."""

    PLANNING = "planning"
    DISPATCH = "dispatch"
    SYNTHESIS = "synthesis"


@dataclass(frozen=True)
class PlanTask:
    """A single sub-task within an expansion plan.

    Produced by the LLM planner or deterministic fallback planner.
    Consumed by the executor dispatch phase.

    Args:
        name: Task identifier (e.g., "compare_performance").
        goal: What this sub-agent should answer or produce.
        constraints: Scope or focus limits for the sub-agent.
        expected_output: Output shape description ("text", "comparison table", etc.).
        mode: Execution mode — inference-only or tool-enabled.
        tools: Tool names available when mode is TOOLED_SEQUENTIAL.
    """

    name: str
    goal: str
    constraints: list[str] = field(default_factory=list)
    expected_output: str = "text"
    mode: SubAgentMode = SubAgentMode.PARALLEL_INFERENCE
    tools: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class ExpansionPlan:
    """A validated expansion plan ready for dispatch.

    Args:
        strategy: "HYBRID" or "DECOMPOSE" — mirrors gateway output.
        tasks: Ordered list of sub-tasks to execute.
        is_fallback: True if generated by the deterministic fallback planner.
    """

    strategy: str
    tasks: list[PlanTask]
    is_fallback: bool = False


@dataclass(frozen=True)
class PhaseResult:
    """Result of a single expansion phase.

    Args:
        phase: Which phase completed.
        duration_ms: Wall-clock time for this phase.
        success: Whether the phase completed without error.
        error: Error description if success is False.
    """

    phase: ExpansionPhase
    duration_ms: float
    success: bool
    error: str | None = None
