"""In-process idempotency guard for inbound chat messages (FRE-392).

Prevents a WebSocket reconnect from triggering a second orchestrator
invocation for the same message.  The guard is keyed by a client-generated
idempotency key (``client_msg_id``) when available, or a SHA-256 content
hash of ``(session_id, message)`` as a fallback for CLI / older clients.

Entries expire after ``ttl_seconds`` (default 120 s), which is long enough
to cover the 39-second duplicate observed in production but short enough
to allow legitimate re-sends of identical text in a new turn.  Entries are
also removed eagerly via ``release()`` when the background task completes,
so immediate retry after an error does not block the user.
"""

from __future__ import annotations

import hashlib
import time
from dataclasses import dataclass, field


@dataclass(frozen=True)
class DeduplicationResult:
    """Result of a deduplication check.

    Attributes:
        is_duplicate: True when this message was already recorded within the TTL.
        original_trace_id: The trace_id of the first (accepted) invocation, or
            None when this is the first occurrence.
    """

    is_duplicate: bool
    original_trace_id: str | None = None


@dataclass
class MessageDeduplicator:
    """In-process idempotency store for chat messages.

    Thread-safety: asyncio is single-threaded, so a plain dict is sufficient.
    No external dependencies — no Redis, no Postgres.

    Attributes:
        ttl_seconds: How long to retain a dedup entry after recording it.
    """

    ttl_seconds: float = 120.0
    # (session_id, dedup_key) → (original_trace_id, recorded_at_monotonic)
    _store: dict[tuple[str, str], tuple[str, float]] = field(default_factory=dict, repr=False)

    def _compute_dedup_key(self, session_id: str, message: str, client_msg_id: str | None) -> str:
        """Derive the dedup key from available identifiers.

        Args:
            session_id: Session UUID string.
            message: Raw message text.
            client_msg_id: Client-generated UUID when present; takes precedence.

        Returns:
            A string key suitable for use in ``_store``.
        """
        if client_msg_id is not None:
            return client_msg_id
        digest = hashlib.sha256((session_id + message).encode()).hexdigest()
        return digest[:16]

    def check_and_record(
        self,
        session_id: str,
        message: str,
        trace_id: str,
        client_msg_id: str | None = None,
    ) -> DeduplicationResult:
        """Check whether this message is a duplicate and record it if not.

        Args:
            session_id: Session UUID string.
            message: Raw user message text.
            trace_id: Freshly-generated trace_id for this invocation.
            client_msg_id: Optional idempotency key generated by the client.

        Returns:
            DeduplicationResult indicating whether this is a duplicate and,
            if so, the trace_id of the original invocation.
        """
        dedup_key = self._compute_dedup_key(session_id, message, client_msg_id)
        store_key = (session_id, dedup_key)
        now = time.monotonic()

        existing = self._store.get(store_key)
        if existing is not None:
            original_trace_id, recorded_at = existing
            if now - recorded_at < self.ttl_seconds:
                return DeduplicationResult(is_duplicate=True, original_trace_id=original_trace_id)

        self._store[store_key] = (trace_id, now)
        return DeduplicationResult(is_duplicate=False)

    def release(
        self,
        session_id: str,
        message: str,
        client_msg_id: str | None = None,
    ) -> None:
        """Remove the dedup entry so the user can immediately re-send.

        Called from the background task's ``finally`` block.  Allows a
        legitimate retry (e.g. after an LLM error) without waiting for TTL
        expiry.

        Args:
            session_id: Session UUID string.
            message: Raw user message text.
            client_msg_id: The same idempotency key used when recording.
        """
        dedup_key = self._compute_dedup_key(session_id, message, client_msg_id)
        self._store.pop((session_id, dedup_key), None)

    def cleanup_expired(self) -> int:
        """Remove all entries that have exceeded the TTL.

        Args:
            (none)

        Returns:
            Number of entries removed.
        """
        now = time.monotonic()
        expired = [
            k
            for k, (_, recorded_at) in self._store.items()
            if now - recorded_at >= self.ttl_seconds
        ]
        for k in expired:
            del self._store[k]
        return len(expired)


_deduplicator = MessageDeduplicator()


def get_deduplicator() -> MessageDeduplicator:
    """Return the module-level singleton deduplicator.

    Returns:
        The shared MessageDeduplicator instance.
    """
    return _deduplicator
