'use client';

import { useEffect, useRef, useState } from 'react';

import { resumeInterrupt } from '@/lib/agui-client';
import type { ExecutionProfile } from '@/lib/types';
import { useSSEStream } from '@/hooks/useSSEStream';

import { ChatInput } from './ChatInput';
import { ChatMessage } from './ChatMessage';
import { ContextBudgetMeter } from './ContextBudgetMeter';
import { ProfileSelector } from './ProfileSelector';
import { ToolIndicator } from './ToolIndicator';

interface StreamingChatProps {
  /** Initial session ID. Generated by the parent if not supplied. */
  sessionId?: string;
}

/**
 * Primary chat interface composing all sub-components.
 *
 * Layout:
 * - Header: Seshat title + selected profile badge + context budget meter
 * - Body:   Scrollable message list (or profile selector for new sessions)
 * - Footer: Tool indicators + chat input
 *
 * Conversation lifecycle:
 * 1. Fresh session — shows ProfileSelector overlay.
 * 2. After profile selected — shows empty chat + input.
 * 3. Messages stream in via AG-UI SSE.
 * 4. INTERRUPT events render an inline approval card.
 */
export function StreamingChat({ sessionId: initialSessionId }: StreamingChatProps) {
  const sessionId = useRef(
    initialSessionId ?? crypto.randomUUID(),
  ).current;

  const [profile, setProfile] = useState<ExecutionProfile>('local');
  const [profileChosen, setProfileChosen] = useState(false);

  const {
    messages,
    isStreaming,
    activeTools,
    contextBudget,
    pendingInterrupt,
    sendMessage,
    resolveInterrupt,
    clearMessages,
  } = useSSEStream();

  // Auto-scroll to bottom on new messages.
  const bottomRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, activeTools]);

  const handleSend = (text: string) => {
    sendMessage(text, sessionId, profile);
  };

  const handleProfileConfirm = () => {
    setProfileChosen(true);
  };

  const handleInterruptChoice = async (choice: string) => {
    try {
      await resumeInterrupt({ sessionId, choice });
      resolveInterrupt(choice);
    } catch {
      // If resume fails the stream is stale — surface nothing; user can retry.
    }
  };

  const handleNewConversation = () => {
    clearMessages();
    setProfileChosen(false);
  };

  return (
    <div className="flex flex-col h-full bg-slate-900 text-slate-100">
      {/* ------------------------------------------------------------------ */}
      {/* Header                                                               */}
      {/* ------------------------------------------------------------------ */}
      <header className="flex items-center justify-between px-4 py-3 border-b border-slate-700 bg-slate-900/80 backdrop-blur-sm flex-shrink-0">
        <div className="flex items-center gap-2">
          <h1 className="text-base font-semibold text-slate-100">Seshat</h1>
          {profileChosen && (
            <span className="text-xs px-2 py-0.5 rounded-full bg-slate-700 text-slate-400 font-mono">
              {profile}
            </span>
          )}
        </div>
        <div className="flex items-center gap-3">
          {profileChosen && messages.length > 0 && (
            <button
              onClick={handleNewConversation}
              className="text-xs text-slate-500 hover:text-slate-300 transition-colors"
            >
              New
            </button>
          )}
        </div>
      </header>

      {/* Context budget meter — spans full width below header */}
      {profileChosen && (
        <ContextBudgetMeter budget={contextBudget} />
      )}

      {/* ------------------------------------------------------------------ */}
      {/* Body                                                                 */}
      {/* ------------------------------------------------------------------ */}
      <main className="flex-1 overflow-y-auto px-4 py-4 space-y-0 scrollbar-thin scrollbar-thumb-slate-700 scrollbar-track-transparent">
        {!profileChosen ? (
          /* ---- Profile selection overlay ---- */
          <div className="flex flex-col items-center justify-center h-full gap-6 max-w-sm mx-auto">
            <div className="text-center">
              <div className="text-3xl mb-2">&#x1F4DA;</div>
              <h2 className="text-lg font-semibold text-slate-100">
                New Conversation
              </h2>
              <p className="text-sm text-slate-400 mt-1">
                Start by choosing an execution profile
              </p>
            </div>
            <ProfileSelector
              selected={profile}
              onSelect={setProfile}
            />
            <button
              onClick={handleProfileConfirm}
              className="w-full py-3 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-medium text-sm transition-colors"
            >
              Start Conversation
            </button>
          </div>
        ) : messages.length === 0 ? (
          /* ---- Empty state ---- */
          <div className="flex flex-col items-center justify-center h-full text-slate-500 gap-2">
            <p className="text-sm">Ask Seshat anything...</p>
          </div>
        ) : (
          /* ---- Message list ---- */
          <>
            {messages.map((msg) => (
              <ChatMessage key={msg.id} message={msg} />
            ))}
            {/* Streaming cursor */}
            {isStreaming && (
              <div className="flex justify-start mb-4">
                <div className="bg-slate-700 rounded-2xl rounded-bl-sm px-4 py-3">
                  <span className="flex gap-1">
                    <span className="w-1.5 h-1.5 rounded-full bg-slate-400 animate-bounce [animation-delay:0ms]" />
                    <span className="w-1.5 h-1.5 rounded-full bg-slate-400 animate-bounce [animation-delay:150ms]" />
                    <span className="w-1.5 h-1.5 rounded-full bg-slate-400 animate-bounce [animation-delay:300ms]" />
                  </span>
                </div>
              </div>
            )}
          </>
        )}

        {/* ---- HITL interrupt card ---- */}
        {pendingInterrupt && (
          <div className="my-4 p-4 rounded-xl border border-amber-700/50 bg-amber-900/20">
            <p className="text-sm font-medium text-amber-300 mb-1">
              Approval needed
            </p>
            <p className="text-sm text-slate-300 mb-3">
              {pendingInterrupt.context}
            </p>
            <div className="flex gap-2 flex-wrap">
              {pendingInterrupt.options.map((option) => (
                <button
                  key={option}
                  onClick={() => handleInterruptChoice(option)}
                  className="px-4 py-1.5 rounded-lg text-sm font-medium border transition-colors
                    border-amber-600 text-amber-300 hover:bg-amber-800/40"
                >
                  {option}
                </button>
              ))}
            </div>
          </div>
        )}

        <div ref={bottomRef} />
      </main>

      {/* ------------------------------------------------------------------ */}
      {/* Footer                                                               */}
      {/* ------------------------------------------------------------------ */}
      {profileChosen && (
        <footer className="flex-shrink-0">
          <ToolIndicator tools={activeTools} />
          <ChatInput
            onSend={handleSend}
            disabled={isStreaming || pendingInterrupt !== null}
          />
        </footer>
      )}
    </div>
  );
}
